server:
  port: 8000
  
spring: 
      #数据库配置
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://negosan0104.mysql.rds.aliyuncs.com:3306/htdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: negosan
    password: '#Nogosan'
 
      
      # 指定静态资源路径
   resources:
        #指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
    static-locations: classpath:/static/

      #热部署--静态资源立即生效
   thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/static/
    suffix: .html
    check-template-location: true
      #热部署生效
   devtools:
    restart:
      enabled: true

   jackson:
      #指定日期格式，比如yyyy-MM-dd HH:mm:ss
     date-format: yyyy-MM-dd HH:mm:ss
      #指定日期格式化时区
     time-zone: GMT+8
  
  
#mybatis配置   
mybatis:
  mapper-locations:
  - classpath*:/mappers/fee/*Mapper.xml
  type-aliases-package:
    com.neusoft.ht.feeservice.model
  

  
#showSql
logging:
  level:
    com.neusoft.ht.fee.mapper: debug
